name: Go Build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64, arm]
        include:
          - goarch: arm
            goarm: 7
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: |
        mkdir -p build-${{ matrix.goarch }}
        GOARCH=${{ matrix.goarch }} GOARM=${{ matrix.goarm }} go build -v -o build-${{ matrix.goarch }}/CloudflareWarpSpeedTest ./...

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: CloudflareWarpSpeedTest-${{ matrix.goarch }}
        path: build-${{ matrix.goarch }}
