name: Go-Releaser

on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64, arm64, arm]
        include:
          - goos: linux
            goarch: mips
            gomips: softfloat
          - goos: linux
            goarch: mipsle
            gomips: softfloat
          - goos: linux
            goarch: mips64
          - goos: linux
            goarch: mips64le
          - goos: linux
            goarch: arm
            goarm: 7
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} GOARM=${{ matrix.goarm }} GOMIPS=${{ matrix.gomips }} go build -ldflags "-X main.Version=${{ github.ref_name }}" -o CloudflareWarpSpeedTest-${{ matrix.goos }}-${{ matrix.goarch }}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: CloudflareWarpSpeedTest-${{ matrix.goos }}-${{ matrix.goarch }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
