name: Go Release

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64, arm]
        include:
          - goos: linux
            goarch: arm
            goarm: 7
        exclude:  # 排除不支持的平台
          - goos: darwin
            goarch: arm
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        run: |
          mkdir -p build-${{ matrix.goos }}-${{ matrix.goarch }}
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} GOARM=${{ matrix.goarm }} go build -v -o build-${{ matrix.goos }}-${{ matrix.goarch }} ./...

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CloudflareWarpSpeedTest-${{ matrix.goos }}-${{ matrix.goarch }}
          path: build-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ matrix.goos == 'linux' && matrix.goarch == 'amd64' }}
        with:
          files: |
            build-linux-amd64/CloudflareWarpSpeedTest
            build-linux-arm64/CloudflareWarpSpeedTest
            build-linux-arm/CloudflareWarpSpeedTest
            build-windows-amd64/CloudflareWarpSpeedTest
            build-windows-arm64/CloudflareWarpSpeedTest
            build-darwin-amd64/CloudflareWarpSpeedTest
            build-darwin-arm64/CloudflareWarpSpeedTest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
