name: Release for armv7l

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Release Go Binary for armv7l
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set APP_VERSION env
      run: echo APP_VERSION=$(basename ${GITHUB_REF}) >> ${GITHUB_ENV}

    - name: Set ldflags as environment variable
      run: echo "LD_FLAGS=-X main.Version=${{ env.APP_VERSION }}" >> ${GITHUB_ENV}

    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: arm
        goarm: 7
        project_path: "."
        binary_name: "CloudflareWarpSpeedTest"
        goversion: "1.22"
        ldflags: "${{ env.LD_FLAGS }}"
